# Generated by Django 6.0.1 on 2026-01-19 21:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canais_vendas', '0001_initial'),
        ('grupo_vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título Principal')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('ean', models.CharField(blank=True, max_length=20, verbose_name='EAN')),
                ('largura', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Largura (cm)')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Altura (cm)')),
                ('profundidade', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Profundidade (cm)')),
                ('peso_fisico', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Peso Físico (kg)')),
                ('titulos_secundarios', models.JSONField(blank=True, default=list, verbose_name='Títulos Secundários')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='ItemFichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código do Item')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantidade por Kit')),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Custo Unitário (R$)')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_ficha', to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item da Ficha Técnica',
                'verbose_name_plural': 'Itens da Ficha Técnica',
                'ordering': ['produto', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_produto', models.CharField(max_length=50, verbose_name='SKU do Produto')),
                ('nome_canal', models.CharField(max_length=100, verbose_name='Nome do Canal')),
                ('nome_grupo', models.CharField(max_length=100, verbose_name='Nome do Grupo')),
                ('imposto', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Imposto (%)')),
                ('operacao', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Operação (%)')),
                ('lucro', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Lucro (%)')),
                ('promocao_perc', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Promoção (%)')),
                ('minimo_perc', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Mínimo (%)')),
                ('ads', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ads (%)')),
                ('comissao', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Comissão (%)')),
                ('frete_aplicado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Frete Aplicado (R$)')),
                ('markup_frete', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Markup Frete')),
                ('markup_venda', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Markup Venda')),
                ('markup_promocao', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Markup Promoção')),
                ('markup_minimo', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Markup Mínimo')),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo (R$)')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda (R$)')),
                ('preco_promocao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Promoção (R$)')),
                ('preco_minimo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Mínimo (R$)')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo da Alteração')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora do Registro')),
                ('canal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_precos', to='canais_vendas.canalvenda', verbose_name='Canal de Venda')),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_precos', to='grupo_vendas.grupocanais', verbose_name='Grupo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_precos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_precos', to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Histórico de Preço',
                'verbose_name_plural': 'Histórico de Preços',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='PrecoProdutoCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usar_calculo_automatico', models.BooleanField(default=True, help_text='Se desmarcado, usa os valores manuais abaixo', verbose_name='Usar Cálculo Automático')),
                ('preco_venda_manual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Preço de Venda (Manual)')),
                ('preco_promocao_manual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Preço Promoção (Manual)')),
                ('preco_minimo_manual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Preço Mínimo (Manual)')),
                ('frete_especifico', models.DecimalField(blank=True, decimal_places=2, help_text='Se preenchido, sobrescreve o frete do canal', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Frete Específico (R$)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos_produtos', to='canais_vendas.canalvenda', verbose_name='Canal de Venda')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos_canais', to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Preço Produto/Canal',
                'verbose_name_plural': 'Preços Produtos/Canais',
                'ordering': ['produto', 'canal'],
                'unique_together': {('produto', 'canal')},
            },
        ),
    ]
