# Generated by Django 5.2.4 on 2026-01-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfichatecnica',
            name='tipo',
            field=models.CharField(choices=[('MP', 'Matéria Prima'), ('TR', 'Terceirizado'), ('EM', 'Embalagem')], default='MP', max_length=2),
        ),
        migrations.AddField(
            model_name='itemfichatecnica',
            name='unidade',
            field=models.CharField(choices=[('UN', 'Unidade'), ('PC', 'Peça'), ('CJ', 'Conjunto'), ('KG', 'Quilograma'), ('G', 'Grama'), ('M', 'Metro'), ('CM', 'Centímetro'), ('M2', 'Metro Quadrado'), ('L', 'Litro'), ('ML', 'Mililitro'), ('CX', 'Caixa'), ('PCT', 'Pacote'), ('PAR', 'Par'), ('JG', 'Jogo')], default='UN', max_length=5),
        ),
    ]
