# Generated by Django 6.0.1 on 2026-01-19 22:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfichatecnica',
            name='unidade',
            field=models.CharField(choices=[('UN', 'Unidade'), ('PC', 'Peça'), ('CJ', 'Conjunto'), ('KG', 'Quilograma'), ('G', 'Grama'), ('M', 'Metro'), ('CM', 'Centímetro'), ('M2', 'Metro Quadrado'), ('L', 'Litro'), ('ML', 'Mililitro'), ('CX', 'Caixa'), ('PCT', 'Pacote'), ('PAR', 'Par'), ('JG', 'Jogo')], default='UN', max_length=5, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='itemfichatecnica',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantidade'),
        ),
    ]
