# Generated by Django 6.0.1 on 2026-01-19 22:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_itemfichatecnica_unidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfichatecnica',
            name='custo_unitario',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Custo Unitário (R$)'),
        ),
    ]
