# Generated by Django 5.2.4 on 2026-01-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_itemfichatecnica_tipo_itemfichatecnica_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='precoprodutocanal',
            name='preco_minimo_manual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='precoprodutocanal',
            name='preco_promocao_manual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
