# Generated by Django 5.2.4 on 2026-01-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_precoprodutocanal_preco_minimo_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicopreco',
            name='preco_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicopreco',
            name='preco_promocao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
