# Generated by Django 6.0.1 on 2026-01-19 22:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_itemfichatecnica_custo_unitario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemfichatecnica',
            options={'ordering': ['produto', 'tipo', 'codigo'], 'verbose_name': 'Item da Ficha Técnica', 'verbose_name_plural': 'Itens da Ficha Técnica'},
        ),
        migrations.AddField(
            model_name='itemfichatecnica',
            name='multiplicador',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Multiplicador'),
        ),
        migrations.AddField(
            model_name='itemfichatecnica',
            name='tipo',
            field=models.CharField(choices=[('MP', 'Matéria Prima'), ('TR', 'Terceirizado'), ('EM', 'Embalagem')], default='MP', max_length=2, verbose_name='Tipo de Item'),
        ),
    ]
