# Generated by Django 5.2.4 on 2026-01-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canais_vendas', '0001_initial'),
        ('produtos', '0004_historicopreco_preco_minimo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='precoprodutocanal',
            options={'verbose_name': 'Preço Produto/Canal', 'verbose_name_plural': 'Preços Produto/Canal'},
        ),
        migrations.AddField(
            model_name='precoprodutocanal',
            name='calculado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última atualização do cálculo'),
        ),
        migrations.AddField(
            model_name='precoprodutocanal',
            name='custo_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='precoprodutocanal',
            name='frete_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='precoprodutocanal',
            name='preco_minimo_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='precoprodutocanal',
            name='preco_promocao_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='precoprodutocanal',
            name='preco_venda_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='precoprodutocanal',
            name='taxa_calculada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='precoprodutocanal',
            unique_together={('produto', 'canal')},
        ),
    ]
