# Generated by Django 5.2.4 on 2026-01-20 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_add_campos_calculados'),
    ]

    operations = [
        migrations.CreateModel(
            name='TituloProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU do Título')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('ean', models.CharField(blank=True, max_length=20, verbose_name='EAN')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulos', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Título de Produto',
                'verbose_name_plural': 'Títulos de Produtos',
                'ordering': ['produto', 'titulo'],
            },
        ),
    ]
