# Generated by Django 5.2.4 on 2026-01-20 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_add_titulo_produto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicopreco',
            options={'ordering': ['-data_registro'], 'verbose_name': 'Histórico de Preço', 'verbose_name_plural': 'Históricos de Preços'},
        ),
        migrations.AddField(
            model_name='historicopreco',
            name='ads',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicopreco',
            name='comissao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicopreco',
            name='grupo_nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='historicopreco',
            name='imposto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicopreco',
            name='lucro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicopreco',
            name='markup_frete',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicopreco',
            name='markup_minimo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicopreco',
            name='markup_promocao',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicopreco',
            name='markup_venda',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicopreco',
            name='minimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicopreco',
            name='operacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicopreco',
            name='peso_produto',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicopreco',
            name='promocao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicopreco',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos', to='produtos.produto'),
        ),
    ]
