# Generated by Django 5.2.4 on 2026-01-20 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_add_historico_completo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tituloproduto',
            name='ean',
        ),
        migrations.RemoveField(
            model_name='tituloproduto',
            name='sku',
        ),
    ]
