# Generated by Django 5.2.4 on 2026-01-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_remove_tituloproduto_ean_remove_tituloproduto_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='precoprodutocanal',
            name='preco_minimo_arredondado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preco Min Arredondado'),
        ),
        migrations.AddField(
            model_name='precoprodutocanal',
            name='preco_promocao_arredondado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preco Promo Arredondado'),
        ),
    ]
