# Generated by Django 6.0.1 on 2026-01-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_precoprodutocanal_preco_minimo_arredondado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='precoprodutocanal',
            name='ads',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ads (%)'),
        ),
        migrations.AddField(
            model_name='precoprodutocanal',
            name='comissao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Comissão (%)'),
        ),
        migrations.AddField(
            model_name='precoprodutocanal',
            name='imposto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Imposto (%)'),
        ),
        migrations.AddField(
            model_name='precoprodutocanal',
            name='lucro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Lucro (%)'),
        ),
        migrations.AddField(
            model_name='precoprodutocanal',
            name='minimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Mínimo (%)'),
        ),
        migrations.AddField(
            model_name='precoprodutocanal',
            name='operacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Operação (%)'),
        ),
        migrations.AddField(
            model_name='precoprodutocanal',
            name='promocao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Promoção (%)'),
        ),
    ]
