# Generated by Django 6.0.1 on 2026-01-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_precoprodutocanal_ads_precoprodutocanal_comissao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='mlb',
            field=models.CharField(blank=True, max_length=50, verbose_name='MLB'),
        ),
        migrations.AddField(
            model_name='produto',
            name='mlb_vinculado',
            field=models.CharField(blank=True, max_length=50, verbose_name='MLB Vinculado'),
        ),
    ]
