# Generated by Django 6.0.1 on 2026-01-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_produto_mlb_produto_mlb_vinculado'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='desconto_estrategico',
            field=models.BooleanField(default=False, verbose_name='Desconto Estratégico'),
        ),
    ]
