# Generated by Django 5.2.4 on 2026-01-27 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canais_vendas', '0002_canalvenda_score'),
        ('grupo_vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupocanais',
            name='canal_referencia_custo',
            field=models.ForeignKey(blank=True, help_text='Se selecionado, o Custo Base será o Preço de Venda deste canal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_referencia', to='canais_vendas.canalvenda', verbose_name='Canal de Referência'),
        ),
        migrations.AddField(
            model_name='grupocanais',
            name='tipo_custo',
            field=models.CharField(choices=[('padrao', 'Custo Padrão (Ficha Técnica)'), ('canal', 'Baseado no Preço de Venda de outro Canal')], default='padrao', max_length=10, verbose_name='Origem do Custo'),
        ),
    ]
