# Generated by Django 5.2.4 on 2026-01-20 13:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupo_vendas', '0001_initial'),
        ('tabela_frete', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Canal')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('herdar_grupo', models.BooleanField(default=True, help_text='Se marcado, usa os percentuais definidos no grupo', verbose_name='Herdar valores do grupo')),
                ('imposto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99.99'))], verbose_name='Imposto (%)')),
                ('operacao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99.99'))], verbose_name='Operação (%)')),
                ('lucro', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99.99'))], verbose_name='Lucro (%)')),
                ('promocao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99.99'))], verbose_name='Promoção (%)')),
                ('minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99.99'))], verbose_name='Mínimo (%)')),
                ('ads', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99.99'))], verbose_name='Ads (%)')),
                ('comissao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99.99'))], verbose_name='Comissão (%)')),
                ('tipo_frete', models.CharField(choices=[('fixo', 'Frete Fixo'), ('tabela', 'Tabela de Frete')], default='fixo', max_length=10, verbose_name='Tipo de Frete')),
                ('frete_fixo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Frete Fixo (R$)')),
                ('nota_vendedor', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Ruim'), (2, '2 - Regular'), (3, '3 - Bom'), (4, '4 - Muito Bom'), (5, '5 - Excelente')], help_text='Nota do vendedor no marketplace (1-5) para cálculo de desconto de frete', null=True, verbose_name='Nota do Vendedor')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canais', to='grupo_vendas.grupocanais', verbose_name='Grupo')),
                ('tabela_frete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canais', to='tabela_frete.tabelafrete', verbose_name='Tabela de Frete')),
                ('tabela_taxa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canais', to='tabela_frete.tabelataxa', verbose_name='Tabela de Taxas (Extras)')),
            ],
            options={
                'verbose_name': 'Canal de Venda',
                'verbose_name_plural': 'Canais de Venda',
                'ordering': ['grupo', 'nome'],
                'unique_together': {('nome', 'grupo')},
            },
        ),
    ]
