# Generated by Django 6.0.1 on 2026-01-19 21:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupo_vendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaFrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Tabela')),
                ('tipo', models.CharField(choices=[('peso', 'Por Peso (kg)'), ('preco', 'Por Preço (R$)')], default='peso', max_length=10, verbose_name='Tipo de Condição')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Tabela de Frete',
                'verbose_name_plural': 'Tabelas de Frete',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RegraFrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Avaliação')),
                ('tipo_condicao', models.CharField(choices=[('if', 'SE'), ('elseif', 'SENÃO SE'), ('else', 'SENÃO')], default='if', max_length=10, verbose_name='Tipo de Condição')),
                ('operador', models.CharField(blank=True, choices=[('lte', '≤ (menor ou igual)'), ('lt', '< (menor que)'), ('gte', '≥ (maior ou igual)'), ('gt', '> (maior que)'), ('eq', '= (igual)')], default='lte', max_length=5, verbose_name='Operador')),
                ('valor_limite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor Limite')),
                ('valor_frete', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor do Frete')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='canais_vendas.tabelafrete', verbose_name='Tabela de Frete')),
            ],
            options={
                'verbose_name': 'Regra de Frete',
                'verbose_name_plural': 'Regras de Frete',
                'ordering': ['tabela', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='CanalVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Canal')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('herdar_grupo', models.BooleanField(default=True, help_text='Se marcado, usa os percentuais definidos no grupo', verbose_name='Herdar valores do grupo')),
                ('imposto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99.99'))], verbose_name='Imposto (%)')),
                ('operacao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99.99'))], verbose_name='Operação (%)')),
                ('lucro', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99.99'))], verbose_name='Lucro (%)')),
                ('promocao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99.99'))], verbose_name='Promoção (%)')),
                ('minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99.99'))], verbose_name='Mínimo (%)')),
                ('ads', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99.99'))], verbose_name='Ads (%)')),
                ('comissao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('99.99'))], verbose_name='Comissão (%)')),
                ('tipo_frete', models.CharField(choices=[('fixo', 'Frete Fixo'), ('tabela', 'Tabela de Frete')], default='fixo', max_length=10, verbose_name='Tipo de Frete')),
                ('frete_fixo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Frete Fixo (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canais', to='grupo_vendas.grupocanais', verbose_name='Grupo')),
                ('tabela_frete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canais', to='canais_vendas.tabelafrete', verbose_name='Tabela de Frete')),
            ],
            options={
                'verbose_name': 'Canal de Venda',
                'verbose_name_plural': 'Canais de Venda',
                'ordering': ['grupo', 'nome'],
                'unique_together': {('nome', 'grupo')},
            },
        ),
    ]
