# Generated by Django 5.2.4 on 2026-01-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canais_vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canalvenda',
            name='score',
            field=models.IntegerField(default=0, help_text='Score usado em tabelas de frete do tipo "Matriz Peso x Score"', verbose_name='Score do Canal'),
        ),
    ]
