# Generated by Django 5.2.4 on 2026-01-20 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaFrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Tabela')),
                ('tipo', models.CharField(choices=[('peso', 'Por Peso (kg)'), ('preco', 'Por Preço (R$)'), ('matriz', 'Matriz Peso × Preço')], default='matriz', max_length=10)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('suporta_nota_vendedor', models.BooleanField(default=False, verbose_name='Desconto por Nota')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tabela de Frete',
                'verbose_name_plural': 'Tabelas de Frete',
            },
        ),
        migrations.CreateModel(
            name='TabelaTaxa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegraFreteMatriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('peso_inicio', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Peso Início')),
                ('peso_fim', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Peso Fim')),
                ('preco_inicio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Início')),
                ('preco_fim', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Fim')),
                ('valor_frete', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Frete')),
                ('ativo', models.BooleanField(default=True)),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_matriz', to='tabela_frete.tabelafrete')),
            ],
            options={
                'verbose_name': 'Regra Matriz',
                'verbose_name_plural': 'Regras Matriz',
            },
        ),
        migrations.CreateModel(
            name='DescontoNotaVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField()),
                ('percentual_desconto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descontos_nota', to='tabela_frete.tabelafrete')),
            ],
        ),
        migrations.CreateModel(
            name='RegraTaxa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_inicio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preco_fim', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_taxa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='tabela_frete.tabelataxa')),
            ],
        ),
    ]
