# Generated by Django 5.2.4 on 2026-01-20 13:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabela_frete', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descontonotavendedor',
            options={'ordering': ['nota']},
        ),
        migrations.AlterModelOptions(
            name='regrafretematriz',
            options={'ordering': ['tabela', 'ordem'], 'verbose_name': 'Regra Matriz (Peso x Preço)', 'verbose_name_plural': 'Regras Matriz'},
        ),
        migrations.AlterField(
            model_name='descontonotavendedor',
            name='nota',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='descontonotavendedor',
            name='percentual_desconto',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterUniqueTogether(
            name='descontonotavendedor',
            unique_together={('tabela', 'nota')},
        ),
        migrations.CreateModel(
            name='RegraFreteSimples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Início (Kg ou R$)')),
                ('fim', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Fim (Kg ou R$)')),
                ('valor_frete', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Frete')),
                ('ativo', models.BooleanField(default=True)),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_simples', to='tabela_frete.tabelafrete')),
            ],
            options={
                'verbose_name': 'Regra Simples (Peso ou Preço)',
                'verbose_name_plural': 'Regras Simples',
                'ordering': ['tabela', 'inicio'],
            },
        ),
    ]
