# Generated by Django 5.2.4 on 2026-01-20 14:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabela_frete', '0002_alter_descontonotavendedor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelafrete',
            name='adicionar_taxa_fixa',
            field=models.BooleanField(default=False, verbose_name='Adicionar Taxa Fixa'),
        ),
        migrations.AddField(
            model_name='tabelafrete',
            name='valor_taxa_fixa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor da Taxa Fixa'),
        ),
    ]
