# Generated by Django 5.2.4 on 2026-01-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabela_frete', '0003_tabelafrete_adicionar_taxa_fixa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regrafretematriz',
            options={'ordering': ['tabela', 'excedente', 'ordem'], 'verbose_name': 'Regra Matriz', 'verbose_name_plural': 'Regras Matriz'},
        ),
        migrations.AlterModelOptions(
            name='regrafretesimples',
            options={'ordering': ['tabela', 'excedente', 'inicio'], 'verbose_name': 'Regra Simples (Peso ou Preço)', 'verbose_name_plural': 'Regras Simples'},
        ),
        migrations.AddField(
            model_name='regrafretematriz',
            name='excedente',
            field=models.BooleanField(default=False, verbose_name='Regra Excedente (>1m)'),
        ),
        migrations.AddField(
            model_name='regrafretematriz',
            name='score_fim',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score Fim'),
        ),
        migrations.AddField(
            model_name='regrafretematriz',
            name='score_inicio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score Início'),
        ),
        migrations.AddField(
            model_name='regrafretesimples',
            name='excedente',
            field=models.BooleanField(default=False, verbose_name='Regra Excedente (>1m)'),
        ),
        migrations.AddField(
            model_name='tabelafrete',
            name='usa_tabela_excedente',
            field=models.BooleanField(default=False, verbose_name='Tabela Diferenciada > 1m'),
        ),
        migrations.AlterField(
            model_name='tabelafrete',
            name='tipo',
            field=models.CharField(choices=[('peso', 'Por Peso (kg)'), ('preco', 'Por Preço (R$)'), ('matriz', 'Matriz Peso × Preço'), ('matriz_score', 'Matriz Peso × Score')], default='matriz', max_length=15),
        ),
    ]
