# Generated by Django 5.2.4 on 2026-01-20 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabela_frete', '0004_alter_regrafretematriz_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraFreteEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('largura_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Largura Mín (cm)')),
                ('altura_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Altura Mín (cm)')),
                ('profundidade_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Profundidade Mín (cm)')),
                ('peso_min', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Peso Mín (kg)')),
                ('valor_frete', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Frete')),
                ('ativo', models.BooleanField(default=True)),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_especiais', to='tabela_frete.tabelafrete')),
            ],
            options={
                'verbose_name': 'Regra Especial',
                'verbose_name_plural': 'Regras Especiais',
                'ordering': ['tabela', 'ordem'],
            },
        ),
    ]
