# Generated by Django 5.2.4 on 2026-01-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabela_frete', '0005_regrafreteespecial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelafrete',
            name='usar_preco_promocao',
            field=models.BooleanField(default=False, help_text='Se marcado, o frete sera calculado com base no preco promocional. O frete convergido do preco promocional sera usado para calcular preco de venda e preco minimo.', verbose_name='Usar Preco Promocao para Frete'),
        ),
    ]
